# Generated by Django 3.2 on 2021-05-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='Price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
